#!/usr/bin/env bash

echo "--> Changing bash prompt"
cat >> ~/.bashrc <<EOF
# Override prompt to fit virtual machine.
case "\$TERM" in
    xterm-*color) PS1='\[\e]0;\u: \w\a\]\[\033[01;32m\]\u@${debian_chroot:+$debian_chroot}\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ ';;
esac
EOF

echo "--> Setting up package build infrastructure"
cat >> ~/.bashrc <<EOF
DEBEMAIL="jp@openmono.com"
DEBFULLNAME="Jens Peter Secher"
export DEBEMAIL DEBFULLNAME
EOF
