#!/usr/bin/env bash

echo "--> Installing package build infrastructure"
apt-get install -y \
	debhelper \
	devscripts \
	gdb-minimal \
	libusb-1.0-0-dev \
	lintian \
	qt5-default \
	qttools5-dev-tools \
	ruby-aruba
