#!/usr/bin/env bash

echo "--> Setting up package build infrastructure"
cat >> ~/.bashrc <<EOF
DEBEMAIL="jp@openmono.com"
DEBFULLNAME="Jens Peter Secher"
export DEBEMAIL DEBFULLNAME
EOF

echo "--> Setting up symlinks"
cd $HOME
[ -e monoprog ] || ln -s /vagrant monoprog
