language: cpp
sudo: required
services: docker
branches:
  only:
    - master
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default qttools5-dev-tools devscripts libusb-1.0-0-dev libudev-dev libqt5serialport5-dev
  - qmake -version
before_script:
  - gem install cucumber
  - gem install aruba
  - cd src
  - ./clean.sh
  - ./setup.sh
script:
  - echo Building on $TRAVIS_OS_NAME...
  - ./compile.sh
  - ./unittest.sh
  - ./acceptancetest.sh
